### ISSUE TITLE
拉起菜单发生错误

### ISSUE THREAD

**Issue by Mepuru** [debumori-osc/Another-Mirai-Native#1]
在使用Cedar的Bilibili插件时，点击可用群按钮会出现报错。
经过长期测试，在MiraiNative中并无该问题。
但是在AnotherMiraiNative中产生了该问题。
![报错弹窗](https://ykanade.cn/wp-content/uploads/2022/08/HHVF7F8VGFN0N9_UMOQ9.png)

**Comment by Mepuru** [comment]
在开发模式下，插件可以正常运作，只是不能正常弹出窗口

**Comment by Hellobaka** [comment]
![image](https://user-images.githubusercontent.com/50934714/185379810-feaf9679-79bf-46ac-b50a-67724ca29223.png)

托盘右键、插件窗口点击窗口按钮均可成功弹出

刚才release了一个版本，试试更新一下吧

**Comment by Mepuru** [comment]
> ![image](https://user-images.githubusercontent.com/50934714/185379810-feaf9679-79bf-46ac-b50a-67724ca29223.png)
> 
> 托盘右键、插件窗口点击窗口按钮均可成功弹出
> 
> 刚才release了一个版本，试试更新一下吧

仍然存在问题。
从控制台呼出群列表既不抛出错误也不响应
从插件管理页面群列表会报拉起菜单错误
另外我注意到您的Bilibili插件时2.3.51版本，我使用的是2.5.94版本

**Comment by Hellobaka** [comment]
> 仍然存在问题。 从控制台呼出群列表既不抛出错误也不响应 从插件管理页面群列表会报拉起菜单错误 另外我注意到您的Bilibili插件时2.3.51版本，我使用的是2.5.94版本

我更新一下试试

**Comment by Mepuru** [comment]
> > 仍然存在问题。 从控制台呼出群列表既不抛出错误也不响应 从插件管理页面群列表会报拉起菜单错误 另外我注意到您的Bilibili插件时2.3.51版本，我使用的是2.5.94版本
> 
> 我更新一下试试

同为Cedar的WeiboPush插件存在控制台无法调起问题

**Comment by Hellobaka** [comment]
> 仍然存在问题。 从控制台呼出群列表既不抛出错误也不响应 从插件管理页面群列表会报拉起菜单错误 另外我注意到您的Bilibili插件时2.3.51版本，我使用的是2.5.94版本

原来不是开源的啊，方便提供一下插件吗

**Comment by Mepuru** [comment]
![](https://ykanade.cn/wp-content/uploads/2022/08/1@4FHEI35ZGR7TFC8V9M7Q.png)
当点击下载FFemg按钮时产生的错误

**Comment by Mepuru** [comment]
> > 仍然存在问题。 从控制台呼出群列表既不抛出错误也不响应 从插件管理页面群列表会报拉起菜单错误 另外我注意到您的Bilibili插件时2.3.51版本，我使用的是2.5.94版本
> 
> 原来不是开源的啊，方便提供一下插件吗

稍等

**Comment by Mepuru** [comment]
[https://ykanade.cn/wp-content/uploads/2022/08/Bilibili.zip](url)
文件地址

**Comment by Hellobaka** [comment]
已修复，请重新下载`CQP.dll`并覆盖，感谢找出的bug

**Comment by Mepuru** [comment]
> 已修复，请重新下载`CQP.dll`并覆盖，感谢找出的bug

[Releases](https://github.com/Hellobaka/Another-Mirai-Native/releases)
这个Releases里的吗

**Comment by Hellobaka** [comment]
是的，最新的重新下载覆盖就好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月18日(周四) 晚上7:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hellobaka/Another-Mirai-Native] 拉起菜单发生错误 (Issue #1)




  
已修复，请重新下载CQP.dll并覆盖，感谢找出的bug
  
Releases
 这个Releases里的吗
