### ISSUE TITLE
禁用插件时会卡住无响应

### ISSUE THREAD

**Issue by MisaLiu** [debumori-osc/Another-Mirai-Native#10]
我又来了，禁用插件后几乎是 100% 触发卡住框架

日志里边啥都没有，也不知道怎么开 debug，只好录一个 gif 贴上来这样子

![MobaXterm_UccuQdFY7g](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/1a922c49-79f0-4fea-a374-075ce24f4480)

系统是 Windows Server 2022 Datacenter 21H2

**Comment by Hellobaka** [comment]
调用系统FreeLibrary函数时无响应了，没有抓到异常，没什么头绪……

**Comment by Hellobaka** [comment]
感觉插件写法有问题，大部分插件都可以正常卸载

**Comment by MisaLiu** [comment]
![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/95796ea9-56c8-44cd-8766-80a826264dfb)
![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/89828446-7a3e-4d6f-a3cf-bcf00619fb16)

我这个插件的退出事件里边没有写逻辑的

**Comment by Hellobaka** [comment]
这个函数没问题，调用正常结束了。只是在释放dll占用时卡死了，是易语言的问题也没准
