### ISSUE TITLE
无法读取群成员信息

### ISSUE THREAD

**Issue by MisaLiu** [debumori-osc/Another-Mirai-Native#11]
RT

![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/ae347d2c-3f29-413b-804d-15a5fb8df50d)

**Comment by Hellobaka** [comment]
本地无法复现，此日志为尝试将群成员信息对象打包为酷Q格式发生异常时，尝试从内存缓存中获取又失败时写出的。检查一下调用目标是否与Bot存在关系。要是没有找到原因，我再给异常加个调试日志看看实际异常是什么

**Comment by MisaLiu** [comment]
( ´_ゝ` ) 脑抽了  仔细检查发现是因为拉取已经爆炸的群的成员信息导致的

**Comment by Hellobaka** [comment]
> ( ´_ゝ` ) 脑抽了 仔细检查发现是因为拉取已经爆炸的群的成员信息导致的

(;´Д`)
