### ISSUE TITLE
点击不带设置菜单的插件的「菜单」按钮时会出错

### ISSUE THREAD

**Issue by MisaLiu** [debumori-osc/Another-Mirai-Native#12]
好像是因为没做检测的原因，应该是好修的

![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/ae8d46da-3ed2-4ce8-b452-23fb83b02e2c)

**Comment by Hellobaka** [comment]
如果你的app.json的menu节点是这样写的就不会异常
```json
    "event":[  
        {
            "id":2,
            "type":2,
            "name":"群消息处理",
            "function":"_eventGroupMsg",
            "priority":30000
        }
    ],
    "menu":[  ],
```

**Comment by MisaLiu** [comment]
> 如果你的app.json的menu节点是这样写的就不会异常
> 
> ```json
>     "event":[  
>         {
>             "id":2,
>             "type":2,
>             "name":"群消息处理",
>             "function":"_eventGroupMsg",
>             "priority":30000
>         }
>     ],
>     "menu":[  ],
> ```

刚检查了一下，是直接将 `menu` 整个键删掉了，应该是这里导致的

**Comment by Hellobaka** [comment]
> 刚检查了一下，是直接将 `menu` 整个键删掉了，应该是这里导致的

删掉节点确实不是合法操作，内容可以是空的但是不能没有节点

**Comment by MisaLiu** [comment]
> > 刚检查了一下，是直接将 `menu` 整个键删掉了，应该是这里导致的
> 
> 删掉节点确实不是合法操作，内容可以是空的但是不能没有节点

了解了 ~~，看来是小时候不懂事导致的~~
