### ISSUE TITLE
/libraries 文件夹里似乎不管是什么后缀的文件都会被加载

### ISSUE THREAD

**Issue by MisaLiu** [debumori-osc/Another-Mirai-Native#13]
RT，给其中一个库文件加了 `*.bak` 后缀以用来备份前一版文件，结果重启后似乎把这一文件也加载上了

![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/c5d653a2-b3a8-4cee-a3bb-37dc56446630)

**Comment by Hellobaka** [comment]
可加载的库文件类型不一定是dll啊，只要能loadlibrary进来的都可以吧（

**Comment by MisaLiu** [comment]
> 可加载的库文件类型不一定是dll啊，只要能loadlibrary进来的都可以吧（

好像也有点道理

不过能不能折中一下，整一个不加载指定后缀的库，比如 `*.disabled` 啥的

**Comment by Hellobaka** [comment]
> 好像也有点道理
> 
> 不过能不能折中一下，整一个不加载指定后缀的库，比如 `*.disabled` 啥的

我觉得放二级目录里就可以了，需要的时候再拿出来
