### ISSUE TITLE
是否有计划加回「事件优先级」？

### ISSUE THREAD

**Issue by MisaLiu** [debumori-osc/Another-Mirai-Native#14]
被天枢拦掉没开启的群的消息搞的难受了，直接在 json 里修改其他插件的事件优先级貌似也没什么卵用，所以来问问

![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/74dc82c6-9067-434c-9e65-57360d017cbd)

**Comment by Hellobaka** [comment]
啊，确实没有实现这个，可以加上

**Comment by Hellobaka** [comment]
31c3939a95cb8f487c83a55179be398af84a4291
