### ISSUE TITLE
偶现框架崩溃

### ISSUE THREAD

**Issue by MisaLiu** [debumori-osc/Another-Mirai-Native#15]
看调用栈貌似是获取群成员信息的时候崩的？

忘了截日志了，看看什么时候再崩一次

![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/aee0e399-6065-4873-b3d3-aea81fa031a0)

**Comment by Hellobaka** [comment]
55c6bb1d63dfc123b70b99fda13c6c58c8d8d478
