### ISSUE TITLE
文件“\conf\Config.json”正由另一进程使用，因此该进程无法访问此文件。

### ISSUE THREAD

**Issue by MisaLiu** [debumori-osc/Another-Mirai-Native#16]
![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/8ef5ae35-2177-424c-a1e2-6f65807e1968)
![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/a1f4394c-ae66-4e61-b2de-dd58db41a1d1)

**Comment by Hellobaka** [comment]
隐藏悬浮窗吧 这个东西bug还挺多的
