### ISSUE TITLE
在框架关闭的情况下删除插件然后开机载入不会正确调用启动相关事件

### ISSUE THREAD

**Issue by MisaLiu** [debumori-osc/Another-Mirai-Native#17]
~我来点炒饭了~

## 复现步骤

1. 载入一个插件，启用它
2. 关闭框架
3. 删除这个插件
4. 启动框架，然后再次添加这个插件

观察到此次添加插件并不会调用插件的启动相关事件（`_eventStartup` 和 `_eventEnable`）👇
![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/a590aa9c-5a79-4c65-b7a5-2b48e402ef8a)

这是正常的调用逻辑👇
![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/507c624c-59d1-4cca-873b-7e70d529a3fe)

**Comment by Hellobaka** [comment]
感觉是老bug了，在启用插件之后需要大退一下框架再启动，这样插件的启用状态就不会错了。如果你是在做调试工作的话，框架没必要重启，可以保持框架开启的情况下，覆盖plugins文件夹下面的插件，之后重载即可
