### ISSUE TITLE
Cedar的WeiboPush插件无法调出控制台

### ISSUE THREAD

**Issue by Mepuru** [debumori-osc/Another-Mirai-Native#2]
WeiboPush0.5.4版本
[https://ykanade.cn/wp-content/uploads/2022/08/weibo-V0.5.4.zip](url)
在"开发"模式中经测试可以正常使用
但无法调出控制台、框架日志未提示且并无报错

**Comment by Hellobaka** [comment]
![image](https://user-images.githubusercontent.com/50934714/185404133-8524274d-3674-4fff-8a05-6fbaeafc62dc.png)
似乎……没问题？

**Comment by Mepuru** [comment]
经过测试，有几率调不出来
调出来了在左上角设置QQ号之后，右侧也无法正常读取
我觉得应该是插件的问题？

**Comment by Hellobaka** [comment]
> 经过测试，有几率调不出来 调出来了在左上角设置QQ号之后，右侧也无法正常读取 我觉得应该是插件的问题？

如果在MiraiNative上能正常用的话，那还是我这个程序的问题……

明天我再研究研究……

**Comment by Hellobaka** [comment]
新版本已尝试修复此bug，请更新后重试窗口拉起
