### ISSUE TITLE
启动AnotherMiraiNative.exe一直卡在初始化...

### ISSUE THREAD

**Issue by RealSeek** [debumori-osc/Another-Mirai-Native#3]
![](https://user-images.githubusercontent.com/66584031/186469908-1d400d0b-ca9a-4763-84b7-71ea55d5f5ca.png)

**Comment by Hellobaka** [comment]
主程序下是否有CQP.dll，如果没有建议从最老的release下载完整压缩包解压之后，在从最新的release下载两个文件，之后覆盖再启动试试。

**Comment by RealSeek** [comment]
> 主程序下是否有CQP.dll，如果没有建议从最老的release下载完整压缩包解压之后，在从最新的release下载两个文件，之后覆盖再启动试试。

就是从最老的解压出来后覆盖的最新release 还是会出现卡在初始化的问题

**Comment by Hellobaka** [comment]
尝试修改`conf\Config.json`中的`Ws_ServerPort`端口为其他端口再尝试，若没有这个键可手动添加

**Comment by RealSeek** [comment]
好的问题解决了 感谢
