### ISSUE TITLE
佬,这怎么填啊

### ISSUE THREAD

**Issue by weizid** [debumori-osc/Another-Mirai-Native#4]
![QQ图片20220924022528](https://user-images.githubusercontent.com/37445278/192033339-98833741-fa27-4205-80ea-252784bc78ec.png)

![QQ图片20220924022525](https://user-images.githubusercontent.com/37445278/192033294-a4e6584a-60d4-4cd1-b4c4-0085e731d73a.png)

**Comment by Hellobaka** [comment]
https://github.com/project-mirai/mirai-api-http#settingyml%E6%A8%A1%E6%9D%BF
https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/WebsocketAdapter.md
文件位于`mirai\config\net.mamoe.mirai-api-http\setting.yml`
