### ISSUE TITLE
[建议]当AMN抛出错误的反馈

### ISSUE THREAD

**Issue by Mepuru** [debumori-osc/Another-Mirai-Native#5]
当AMN抛出错误的时候，希望通过一些方式来反馈到Bot主
例:
在AMN设置报错反馈至某QQ
通过AMN调用Mirai消息发送将报错信息传给Bot主
![开幕雷击](https://user-images.githubusercontent.com/64205945/193444625-0a383197-35f4-4726-9662-2344bee3b2f6.png)
一登服务器一看铺满一桌面...

**Comment by KaRuichin** [comment]
![@C1)P4P2ET 51XY458`G 64](https://user-images.githubusercontent.com/69111766/193444755-2a35651d-d8fc-4c8e-a410-9e0f1246aa63.jpg)

**Comment by Hellobaka** [comment]
处理插件报错并不是框架的责任，框架弹出报错窗口只是防止框架崩溃的手段，插件应当对自己的插件可能发生的错误负责（虽说这次是框架现版本的bug吧）
