### ISSUE TITLE
试用建议0_0

### ISSUE THREAD

**Issue by miraiuser9528** [debumori-osc/Another-Mirai-Native#7]
1.是否日志的前面一个日志类型（文本）可留空。现在貌似会直接报一个错叫捕捉异常，看了半天发现是因为日志前面一个字符串留空了。但是之前这个应该不是必须要传的。

2.需要使用的dll 可否安装指定到下一层目录中，比如.\libraries\下面，现在所有要用到的dll都在根目录，比较混乱0_0，
或者是否可以兼容一下，也可以从.\libraries\ 目录下找dll什么的

3.部分插件测试，遇到问题，需要关闭another-Mirai-Native时，右下角点图标选退出会报错，然后没有退出
只能从任务管理器里强关

**Comment by Hellobaka** [comment]
1. 我认为写日志的目的是为了让使用者了解插件运行的状态 日志类型的来源能够很好的区分这些日志 另外在这条issue发送之前已经更新了这一表现 现表现为"空标题"而不是"异常捕获"
2. 有待验证可行性
3. 弹出致命错误时请直接点击报错窗口的退出

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月7日(周一) 中午1:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [debumori-osc/Another-Mirai-Native] 试用建议0_0 (Issue #7)




 
1.是否日志的前面一个日志类型（文本）可留空。现在貌似会直接报一个错叫捕捉异常，看了半天发现是因为日志前面一个字符串留空了。但是之前这个应该不是必须要传的。
 
2.需要使用的dll 可否安装指定到下一层目录中，比如.\libraries\下面，现在所有要用到的dll都在根目录，比较混乱0_0，
 或者是否可以兼容一下，也可以从.\libraries\ 目录下找dll什么的
 
3.部分插件测试，遇到问题，需要关闭another-Mirai-Native时，右下角点图标选退出会报错，然后没有退出
 只能从任务管理器里强关

**Comment by miraiuser9528** [comment]
好的，谢谢解答

主要因为mirai前面一个日志标题内容，在命令行里显示是直接连在插件名称后面了，导致看起来非常乱。
所以有一些之前酷Q的插件作者，已经修改去掉了日志标题，直接在后面日志内容里面写标题。

之前试用这个会导致一堆的捕获异常，改成“空标题”可能也是表现成出现大量的“空标题”，或者是否可以简单一个字，“空”

dll的问题还麻烦看看是否方便优化合并放在一个目录下，至少也允许放在某个指定目录下，不然根目录下一堆的dll 囧

最后真的做的挺好的，调插件不用再频繁重启机器人了，感谢

**Comment by Hellobaka** [comment]
我不好说 有的插件喜欢自己找dll 如果藏起来就会爆炸 举个例子 比如说天枢 这个插件会自己找主目录下的bin/zlib.dll 哪怕dll放在主目录下面都会报错
( ᑭ`д´)ᓀ))д´)ᑫ
当然能放在同一个目录里再好不过 容我研究研究可行性



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月7日(周一) 下午3:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [debumori-osc/Another-Mirai-Native] 试用建议0_0 (Issue #7)




 
好的，谢谢解答
 
主要因为mirai前面一个日志标题内容，在命令行里显示是直接连在插件名称后面了，导致看起来非常乱。
 所以有一些之前酷Q的插件作者，已经修改去掉了日志标题，直接在后面日志内容里面写标题。
 
之前试用这个会导致一堆的捕获异常，改成“空标题”可能也是表现成出现大量的“空标题”，或者是否可以简单一个字，“空”
 
dll的问题还麻烦看看是否方便优化合并放在一个目录下，至少也允许放在某个指定目录下，不然根目录下一堆的dll 囧
 
最后真的做的挺好的，调插件不用再频繁重启机器人了，感谢

**Comment by Hellobaka** [comment]
经过测试，似乎是可行的（至少我的插件还在正常工作）

**Comment by miraiuser9528** [comment]
233,我记得天枢是个超级霸道的插件……
可以设置直接拦截其他插件的消息好像
说话天枢还有源码嘛0_0
还是只剩dll和json了……现在还有哪里有下载么……

早年的酷q插件丢一个少一个……

**Comment by Hellobaka** [comment]
天枢是付费插件 没有源码的
https://wwu.lanzouw.com/iBN0k0fgowng
https://wwu.lanzouw.com/iNRip0fgoxyd

**Comment by miraiuser9528** [comment]
emmm遇到了一些问题
似乎卸载插件会炸？无法退出，然后只能每次从任务管理器里强关？

调试的时候插件是正常运行的，退出会5秒没反应，然后报个错，无法退出
这个需要截图出来吗？

啊对了对了，现在下载更新，dll可以丢某个目录了吗?
我看好像exe还是16天前的0_0

**Comment by Hellobaka** [comment]
有预构建的哦 https://github.com/debumori-osc/Another-Mirai-Native/actions
点开最新的一个 在下面找Artifacts下载就行了

**Comment by Hellobaka** [comment]
新版本已发布
