### ISSUE TITLE
能正常处理消息但不能发送消息

### ISSUE THREAD

**Issue by MisaLiu** [debumori-osc/Another-Mirai-Native#9]
* Mirai 版本：`2.16.0`
* Mirai HTTP API 版本：`2.9.1`
* AMN 版本：`1.6.3`

具体表现为：能收到消息，能处理消息，日志虽然显示了发送消息但实际上并没有发出去

![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/1c635eb0-3433-4f84-b2ac-c3cc943baa9e)
![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/1635f9da-35e5-41e0-addf-82b866f6c518)

**Comment by Hellobaka** [comment]
若日志显示发送，但是Mirai端没有发送日志，可能是AMN框架拼接发送参数错误。请提供测试插件我来试试

**Comment by MisaLiu** [comment]
> 若日志显示发送，但是Mirai端没有发送日志，可能是AMN框架拼接发送参数错误。请提供测试插件我来试试

[com.misaliu.robotinfo.zip](https://github.com/debumori-osc/Another-Mirai-Native/files/13852514/com.misaliu.robotinfo.zip)

**Comment by Hellobaka** [comment]
> 若日志显示发送，但是Mirai端没有发送日志，可能是AMN框架拼接发送参数错误。请提供测试插件我来试试

确实参数拼接有问题，MiraiAPIHttp返回了400。修好了我会发布一个版本

**Comment by Hellobaka** [comment]
![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/50934714/50a11b42-bcea-4cc5-a50c-bb8403e6f05d)

已修复

**Comment by MisaLiu** [comment]
更新测试后发现发信会卡在「处理中」，并且处理耗时非常长，而即使最后处理完毕也依旧不能发送带表情的消息，纯文本消息测试没有问题

感觉像是我这边的问题，不过我没有什么头猪了

![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/f34ec5fb-8b3c-4158-9a76-c48b9c0ca87d)
![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/f28f9d6a-967a-43b1-8b96-d1924fb72c97)

**Comment by MisaLiu** [comment]
这会突然又好了 ( ´_ゝ` )，虽然还是处理了老久，可能是签名服务器出什么问题了

![image](https://github.com/debumori-osc/Another-Mirai-Native/assets/62408957/174d7008-9188-4e6d-ab46-cf3410983b62)

**Comment by Hellobaka** [comment]
嗯……我这的mirai版本是2.15.0，没准也许可能和这个有关系？

**Comment by MisaLiu** [comment]
不到哇，我等会试试降级
